//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// DeleteResponse defines model for DeleteResponse.
type DeleteResponse struct {
	Message *string `json:"message,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`
}

// ErrorResponse RFC 7807 Problem Details
type ErrorResponse struct {
	// Detail Human-readable error message
	Detail *string `json:"detail,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short title of the error
	Title *string `json:"title,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Message *string `json:"message,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`
}

// LoginData defines model for LoginData.
type LoginData struct {
	Token *string   `json:"token,omitempty"`
	User  *UserData `json:"user,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginSuccessResponse defines model for LoginSuccessResponse.
type LoginSuccessResponse struct {
	Data    *LoginData `json:"data,omitempty"`
	Message *string    `json:"message,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`
}

// UserData defines model for UserData.
type UserData struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     *string    `json:"email,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Name      *string    `json:"name,omitempty"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Data    *[]UserData `json:"data,omitempty"`
	Message *string     `json:"message,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`
}

// UserSuccessResponse defines model for UserSuccessResponse.
type UserSuccessResponse struct {
	Data    *UserData `json:"data,omitempty"`
	Message *string   `json:"message,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`
}

// UserId defines model for UserId.
type UserId = int64

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit Maximum number of users to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate a user and return a JWT token
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// List users with optional limit
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// Register a new user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Delete a user by ID
	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id UserId)
	// Get a user by ID
	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id UserId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id UserId

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/auth/login", wrapper.LoginUser)
	m.HandleFunc("GET "+options.BaseURL+"/health", wrapper.HealthCheck)
	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{id}", wrapper.GetUser)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xY3VPjNhD/VzRqH30kHLQceaPQ47ihMwwfvQcm01HsTaw7WTLSOpAy+d87K9lx/EFJ",
	"Z0LKG45Wq99+/XaXZx6bLDcaNDo+eua5sCIDBOu/7hzYi4T+SsDFVuYojeYjfqflQwGscGCZTECjnEqw",
	"POKSTnOBKY+4FhnwEZcJj7iFh0JaSPgIbQERd3EKmSDFU2MzgSSn8ddDHnFc5BA+YQaWL5fLStxDOrUg",
	"EAjYNTwU4NCjtiYHixK8CGRCqobu8MtKt0Mr9YwvK4zPPBNPl6BnmPLR/nAY8Uzq6vug51ounHs0Nmld",
	"PfrYuPmpc3O57on78Hq0QrfSOl5dNJPvECM9eQYKEK7B5UY76BqdgXNi5g86cB0KLFw3jF9ub69YOGSx",
	"SaDP+z1QfrfW2HUkTa3Xn0/Z0afhEbuyZqIgY2eAQipHFjYgJ/73HlhFJvQHCyIREwUM6DlW2Rdt1byI",
	"o0TVY8RNaiwyf8jMlGFa4uB9Me146AsIhem7CNalmUl9JlB0UaD5AboXAxU2HfxsYcpH/KdBTRKDshYH",
	"VIJe78vPbqNCG6VW19b+a7W1UVF5lDdFHINzL0crKb33b96o3byMdhneVRQ6qGNPlMlfAhuOTgTCB5RZ",
	"byWt4tI5kclGZF0z6gZVQtgvpcPXPS8RMrd5Qq7eEtaKxf8Qka2k1Lo9O8NP+iAurMTFDeEIcCcgLNiT",
	"giqv+vpc5cLXb7e8bNGkKZzWj6WIeejiUk9NzyxBQ0QmtJhBBhqZ0AkTBaY0VcSChNjJ1QVfMTU/Nx+u",
	"lFiUv87BuqBof2+4NySHmBy0yCUf8YO94d6BJwFMvSED0jxQVKw+KCawE4XGP0XDTmAFglUOLuDwN5Ms",
	"fFEZjaD9HZHnqgQ4+O6M11ePNa9yRcWNyyZx0XjkfwiZ40F/HA63+3Y7PT2GZlS8HHNBcFoo8uvhcH9r",
	"OJozRA+ACz0XSiYstuAHTKFcyM4iy4Rd8BE/qZMEmAjDKCWPBSysZoJ9/XbLQo+LOIqZo7ZA8edjUjRI",
	"fZMmoDPoyYLQw09TiH/wNwxIa1To8cQN2LmMgUnHAmTPaL8MD3YXjDUIhRZzIRVNZq14BEtYXHqs8njp",
	"5uBzCpJ70eXUDO68RNRYRO7bnPGHeJJZkTFdZBOwNKB5xQxNGf1qFXkowC7qXUTJTCJfXz8SmIpCIR99",
	"pKk/qK13gPKrhzjHb5gSnb7YExHvJjLWSphDslapatGKC6kq/fMoMWXG6xCKVd6oIhWCM6ahq5cX69Xr",
	"jYixu9ttxI77W/X8BuToW1Y5X7U8Tyw53F1h/kkcGZpkWE88gOPdAfCuEIqWtQWDJ+mwTdPXMJMOSYpp",
	"ePSJ2JNzK3IYPMtkGSqTFt5uFoZFuMzCFkv0mVKLDMp/Z7xp8bb29JdcFqzry54d9tg7Te3QWPk3JOHx",
	"wx1njjbIpqbQSWPy9LFcnznvxxSzOqeCk6umP1mwi7NeHuvtMueA7zZ7/gsBvUT+O6agalC7OGPlevge",
	"MmmVKueAr+VJSD077581Lk0sFEtgDsrkfkMJsjzihVXlgjMaDBTJpcbh6Pj4+NinSflQZzFrDkrlbFLO",
	"ScuoLX7SWIbqC36U7Yq39qlaPpi7HC//CQAA//9YIWh49BUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
